# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['App.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app_icon.ico', '.'),
        ('ImageAssets\\UI\\lux\\*.png', 'ImageAssets\\UI\\lux'),
        ('ImageAssets\\UI\\pack\\easy\\*.png', 'ImageAssets\\UI\\pack\\easy'),
        ('ImageAssets\\UI\\pack\\hard\\*.png', 'ImageAssets\\UI\\pack\\hard'),
        ('ImageAssets\\UI\\pack\\level\\*.png', 'ImageAssets\\UI\\pack\\level'),
        ('ImageAssets\\AppUI\\*.png', 'ImageAssets\\AppUI'),
        ('ImageAssets\\AppUI\\font\\*.ttf', 'ImageAssets\\AppUI\\font'),
        ('ImageAssets\\AppUI\\affinity\\*.png', 'ImageAssets\\AppUI\\affinity'),
        ('ImageAssets\\AppUI\\selected\\*.png', 'ImageAssets\\AppUI\\selected'),
        ('ImageAssets\\UI\\*.png', 'ImageAssets\\UI'),
        ('ImageAssets\\UI\\battle\\*.png', 'ImageAssets\\UI\\battle'),
        ('ImageAssets\\UI\\battle\\ego\\*.png', 'ImageAssets\\UI\\battle\\ego'),
        ('ImageAssets\\UI\\battle\\sins\\*.png', 'ImageAssets\\UI\\battle\\sins'),
        ('ImageAssets\\UI\\end\\*.png', 'ImageAssets\\UI\\end'),
        ('ImageAssets\\UI\\event\\*.png', 'ImageAssets\\UI\\event'),
        ('ImageAssets\\UI\\event\\sinprob\\*.png', 'ImageAssets\\UI\\event\\sinprob'),
        ('ImageAssets\\UI\\grab\\*.png', 'ImageAssets\\UI\\grab'),
        ('ImageAssets\\UI\\grab\\card\\*.png', 'ImageAssets\\UI\\grab\\card'),
        ('ImageAssets\\UI\\grab\\levels\\*.png', 'ImageAssets\\UI\\grab\\levels'),
        ('ImageAssets\\UI\\pack\\*.png', 'ImageAssets\\UI\\pack'),
        ('ImageAssets\\UI\\move\\*.png', 'ImageAssets\\UI\\move'),
        ('ImageAssets\\UI\\shop\\*.png', 'ImageAssets\\UI\\shop'),
        ('ImageAssets\\UI\\start\\*.png', 'ImageAssets\\UI\\start'),
        ('ImageAssets\\UI\\shop\\buy\\*.png', 'ImageAssets\\UI\\shop\\buy'),
        ('ImageAssets\\UI\\shop\\fuse\\*.png', 'ImageAssets\\UI\\shop\\fuse'),
        ('ImageAssets\\UI\\shop\\cost\\*.png', 'ImageAssets\\UI\\shop\\cost'),
        ('ImageAssets\\UI\\teams\\Bleed\\*.png', 'ImageAssets\\UI\\teams\\Bleed'),
        ('ImageAssets\\UI\\teams\\Bleed\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Bleed\\gifts'),
        ('ImageAssets\\UI\\teams\\Burn\\*.png', 'ImageAssets\\UI\\teams\\Burn'),
        ('ImageAssets\\UI\\teams\\Burn\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Burn\\gifts'),
        ('ImageAssets\\UI\\teams\\Charge\\*.png', 'ImageAssets\\UI\\teams\\Charge'),
        ('ImageAssets\\UI\\teams\\Charge\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Charge\\gifts'),
        ('ImageAssets\\UI\\teams\\Poise\\*.png', 'ImageAssets\\UI\\teams\\Poise'),
        ('ImageAssets\\UI\\teams\\Poise\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Poise\\gifts'),
        ('ImageAssets\\UI\\teams\\Rupture\\*.png', 'ImageAssets\\UI\\teams\\Rupture'),
        ('ImageAssets\\UI\\teams\\Rupture\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Rupture\\gifts'),
        ('ImageAssets\\UI\\teams\\Sinking\\*.png', 'ImageAssets\\UI\\teams\\Sinking'),
        ('ImageAssets\\UI\\teams\\Sinking\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Sinking\\gifts'),
        ('ImageAssets\\UI\\teams\\Tremor\\*.png', 'ImageAssets\\UI\\teams\\Tremor'),
        ('ImageAssets\\UI\\teams\\Tremor\\gifts\\*.png', 'ImageAssets\\UI\\teams\\Tremor\\gifts'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app_icon.ico'],
)
